### ISSUE TITLE
Uncertainpy. for coupled differential equations

### ISSUE THREAD

**Issue by skhan1020** [simetenn/uncertainpy#42]
Can uncertainpy be used to calculate uncertainties in coupled differential systems ? At present, it seems like this feature is not supported.

**Comment by simetenn** [comment]
Yes, Uncertainpy treats the model as a black box and can be used to calculate the uncertainties in such systems.

**Comment by skhan1020** [comment]
Thanks a lot! I can get it to work now. I do have a couple of questions -

1. In the coffee_cup example, is the uncertainty being calculated using the
Polynomial Chaos Expansion (PCE) by default ?
2. The Sobol Indices calculated using uncertainpy are turning out to be
different from the ones directly calculated from SALib library. Is there a
reason for this ?

Souratosh.

**Comment by simetenn** [comment]
Hi, sorry for the delayed answer.

1. Yes, the Polynomial Chaos Expansion is the default method used.
2. There can be a couple of reasons, but it is hard to say without more information. If you use Sobol Indices calculated using PCE then there might be a difference due to different methods, as neither method gives you the analytical solution. If you use the Monte Carlo method  Uncertainpy uses a version of SALib, so they should be similar. But there might be differences due the arguments used in Uncertainpy vs the arguments used in the SALib method. There are also random numbers involved which can cause of some differences.
